[profile.default]
src = 'src'
test = 'test'
out = 'out'
script = 'script'
broadcast = 'broadcast'
cache_path = 'cache'
libs = ['lib']
solc = "0.8.18"

[rpc_endpoints]
sepolia = "${SEPOLIA}"
anvil = "${ANVIL}"
base = "${BASE}"
taiko = "${TAIKO}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
