[profile.default]
src = 'packages/contracts/src'
test = 'packages/contracts/test'
out = 'packages/contracts/out'
script = 'packages/contracts/script'
broadcast = 'packages/contracts/broadcast'
cache_path = 'packages/contracts/cache'
libs = ['packages/contracts/lib']
solc = "0.8.18"
chain_id = 31337
fs_permissions = [{ access = "read-write", path = "./packages/contracts/"}]

[profile.default.model_checker]
contracts = { 'packages/contracts/src/DocRegistry.sol' = [ 'DocRegistry' ], 'packages/contracts/src/DocRegistryL2.sol' = [ 'DocRegistryL2' ] }
# engine = 'chc'
timeout = 15000
targets = [ 'assert' ]

[rpc_endpoints]
sepolia = "${SEPOLIA}"
anvil = "${ANVIL}"
base = "${BASE}"
taiko = "${TAIKO}"
optimism = "https://mainnet.optimism.io"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
